"""Claude-visible text, spelled once (v2.16.0).

Every constant here is text the MODEL reads — through an injection, a
generated file the forced reminder tells it to open, or a recall frame —
or text the user reads in one of those files. Keeping it in one module is
what "prompt management" means in this plugin: `/cc-mem inject-show
--templates` lists each template and its size, and a wording change is one
edit instead of a hunt through six modules.

Rules for this module:
  * Constants and placeholder templates ONLY. No rendering, no
    neutralisation (`tools/contracts.py`'s render-path set names the
    renderers, and this is not one), no imports from the package — it
    must be importable by anything, including a checker that runs nothing.
  * The handshake ack (`ACK_PREFIX` / `ACK_TEMPLATE`) stays in
    `core/progress.py`: the demand and its detector share ONE spelling
    there, and the falsification case `r15ackspell` holds them together.
  * `RESUME_TRIGGERS` is the one resume vocabulary. `hooks/user_prompt.py`
    types the first prompt with it, `hooks/session_start.py` prints it in
    the RESUME PROTOCOL, and `core/recall.py` refuses to retrieve on it —
    three copies of that set drifted before this module existed.
    i18n Tier 3: bilingual by design; do not reduce it to English.
"""

# ── Resume protocol ─────────────────────────────────────────────────────────
RESUME_TRIGGERS = (
    "", "继续", "接着", "接着做", "接着干", "继续干",
    "resume", "continue", "go on", "keep going",
)
# Acknowledgements that are not questions either. Only `core.recall` gates
# on these; they are not resume signals and type no prompt.
ACK_TOKENS = (
    "ok", "okay", "yes", "no", "好", "好的", "行", "对", "是", "嗯",
    "go", "next", "下一步",
)


def _quoted_rows(tokens, per_row):
    rows, row = [], []
    for tok in tokens:
        row.append('"" (empty)' if tok == "" else f'"{tok}"')
        if len(row) == per_row:
            rows.append("    " + "  ·  ".join(row) + "  ·")
            row = []
    if row:
        rows.append("    " + "  ·  ".join(row))
    if rows and rows[-1].endswith("  ·"):
        rows[-1] = rows[-1][:-3]
    return tuple(rows)


# The RESUME PROTOCOL whitelist as the forced reminder prints it.
RESUME_TRIGGER_LINES = _quoted_rows(RESUME_TRIGGERS, per_row=5)

# ── The forced handoff reminder (hooks/session_start.py) ───────────────────
HANDSHAKE_TITLE = "CC-MEMORY HANDOFF — MANDATORY READ-FIRST PROTOCOL"
HANDSHAKE_LEAD = "Before responding to any user request in this session, you MUST:"
HANDSHAKE_READ_STEP = "  {n}. Use the Read tool on `{rel}` (absolute: `{abs}`)."
HANDSHAKE_ACK_LEAD = "After reading, explicitly state in your first reply:"
RESUME_PROTOCOL_HEAD = "RESUME PROTOCOL — if the user's first message is exactly one of:"
RESUME_PROTOCOL_STEPS = (
    "  then DO NOT ask for clarification. Instead:",
    "    1. Read PROGRESS.md §3 (Open Todos) and §4 (Plan).",
    "    2. If §3 has at least one open todo, announce",
    '       "Resuming prior task: <todos[0].content>" and start executing it.',
    "    3. If §3 is empty but §4 (Plan) is non-empty, follow the plan's first step.",
    "    4. If both are empty, fall back to a one-sentence prior-progress",
    '       summary plus "what would you like to do next?".',
)
HANDSHAKE_WHY = (
    "Why: this is the project's handoff contract (single source of truth).",
    "Skipping it risks duplicating work or contradicting prior decisions.",
    "Spec: `docs/CONTRACTS.md#handoff-contract`.",
)

# ── Query-time recall frame (core/recall.py) ───────────────────────────────
RECALL_FRAME_OPEN = "<cc-memory-recall>"
RECALL_FRAME_CLOSE = "</cc-memory-recall>"
RECALL_PREAMBLE = ("{n} stored memory(ies) matched this message "
                   "(lexical retrieval — may be irrelevant; ignore if so):")

# ── Generated documents ────────────────────────────────────────────────────
PROGRESS_MD_NOTICE = (
    "> SINGLE SOURCE OF TRUTH for session handoff. Always full-rewrite from SQLite",
    "> table `progress`. **Never append. Never patch by hand.**",
)
PROGRESS_MD_FOOTER = (
    "---",
    "*This file is the handoff contract for the next session. Read it FIRST.*",
    "*Spec: `docs/CONTRACTS.md#handoff-contract` · Anti-patch contract: "
    "`docs/CONTRACTS.md#anti-patch-contract`*",
)
# Three lines where there were sixteen (v2.16.0, B7): the file is one the
# forced reminder used to make Claude open every session, and 43% of it was
# a maintainer's note.
MEMORY_MD_NOTICE = (
    "<!--",
    "  AUTO-GENERATED by cc-memory. DO NOT EDIT THIS FILE BY HAND. Regenerated after",
    "  every save, consolidation and idle reorg; add a fact with "
    "`/cc-mem add <category> \"<content>\"` or `/save-memories`.",
    "-->",
)
MEMORY_MD_FOOTER = (
    "---",
    "*Anti-patch contract: see `docs/CONTRACTS.md#anti-patch-contract` · "
    "`/cc-mem stats` · `/cc-mem consolidate`*",
)
PLAN_MD_HEADER = (
    "# PLAN",
    "",
    "> AUTO-GENERATED by cc-memory · DO NOT EDIT THIS FILE BY HAND",
    "> Source of truth: SQLite `plan_active` table. Edit via",
    "> `/cc-mem plan-set` (manual replace), Claude's plan mode",
    "> (auto-captured), or `/cc-mem plan-replan` (force re-refine).",
    "",
)

# ── Topic summaries without a model (core/consolidate.py) ──────────────────
# A fallback summary names the topic and counts its rows; it does NOT state
# the facts, so a topic carrying one is not "covered": the critical layer of
# the injection still shows the rows (`_build_topics_layer` tests this
# prefix). Before v2.16.0 the fallback was the eight top facts verbatim, and
# the Knowledge Base layer then repeated them above the Critical layer.
FALLBACK_SUMMARY_PREFIX = "(no-LLM summary) "
